window.SOMA_PRODUCTS = Object.freeze([
  { id: "sillon-alba", name: "Sillón Alba", category: "Mobiliario", type: "Butaca de roble y lino", price: 349, sku: "SOM-ALB-001", color: "Lino natural", material: "Roble macizo y tapizado de lino", size: "72 × 78 × 76 cm", weight: "14 kg", stock: 12, tag: "Nuestro favorito", description: "Tu nuevo lugar para no hacer nada. Alba combina una estructura de roble de líneas suaves con un asiento generoso de lino natural. Una pieza que invita a bajar el ritmo, abrir un libro y quedarse un poco más.", care: "Retira el polvo con un paño suave. Limpia el tapizado con un paño ligeramente humedecido, sin productos abrasivos." },
  { id: "lampara-duna", name: "Lámpara Duna", category: "Iluminación", type: "Luz cálida, formas orgánicas", price: 89, sku: "SOM-DUN-002", color: "Terracota", material: "Cerámica esmaltada y pantalla de algodón", size: "Ø 32 × 45 cm", weight: "2,4 kg", stock: 24, tag: "Nueva colección", description: "La luz de las últimas horas del día, cuando tú quieras. Una base de cerámica en tono terracota sostiene una pantalla de algodón que filtra la luz con delicadeza. Perfecta para una mesita o ese rincón que pide calidez.", care: "Limpia la base con un paño seco y la pantalla con un cepillo suave. Casquillo E27, bombilla LED no incluida." },
  { id: "jarron-tierra", name: "Jarrón Tierra", category: "Decoración", type: "Cerámica con carácter", price: 39, sku: "SOM-TIE-003", color: "Arcilla rojiza", material: "Gres con acabado mate", size: "Ø 18 × 28 cm", weight: "1,2 kg", stock: 31, tag: "", description: "Bonito con flores. Igual de bonito sin ellas. Su silueta escultórica y su acabado mate celebran la sencillez de la arcilla. Las pequeñas variaciones de textura hacen que cada pieza de esta colección imaginaria sea especial.", care: "Lava a mano con agua tibia. Seca antes de colocar sobre superficies delicadas." },
  { id: "mesa-noma", name: "Mesa Noma", category: "Mobiliario", type: "El roble en su forma más simple", price: 159, sku: "SOM-NOM-004", color: "Roble miel", material: "Madera de roble y acabado al aceite", size: "Ø 60 × 42 cm", weight: "8 kg", stock: 9, tag: "", description: "Un café, una conversación, tu revista favorita. Noma hace sitio a los pequeños rituales. Su tablero redondo y sus tres patas de madera crean una mesa auxiliar ligera a la vista y llena de posibilidades.", care: "Utiliza posavasos. Limpia con un paño ligeramente húmedo y seca de inmediato. Incluye instrucciones y kit de montaje." },
  { id: "cojin-brisa", name: "Cojín Brisa", category: "Textil", type: "Textura que abraza", price: 29, sku: "SOM-BRI-005", color: "Verde oliva", material: "Funda de algodón y lino, relleno reciclado", size: "45 × 45 cm", weight: "0,6 kg", stock: 45, tag: "Pequeños placeres", description: "A veces, renovar un espacio es así de sencillo. Una textura suave, un verde tranquilo y un relleno mullido para dar una nueva vida a tu sofá. Brisa es ese pequeño detalle que hace que todo encaje.", care: "Funda desenfundable con cremallera oculta. Lavar a 30 °C, ciclo delicado. No usar secadora." },
  { id: "espejo-arco", name: "Espejo Arco", category: "Decoración", type: "Una ventana a más luz", price: 119, sku: "SOM-ARC-006", color: "Roble natural", material: "Marco de roble y vidrio de 4 mm", size: "50 × 80 × 3 cm", weight: "5,2 kg", stock: 17, tag: "", description: "Abre tu casa a la luz. Arco combina un perfil de madera natural con una forma redondeada que suaviza cualquier pared. En el recibidor, el dormitorio o sobre una cómoda, siempre encuentra su lugar.", care: "Limpia el cristal con un producto específico y el marco con un paño seco. Incluye soportes; elige los anclajes adecuados para tu pared." }
].map(function (p) {
  p.images = [1, 2, 3].map(function (n) { return "assets/images/" + p.id + "-" + n + ".svg"; });
  return Object.freeze(p);
}));
